#!/usr/bin/env python

import sys,csv

if sys.argv[1] == '--skip-header':
    skip=True
    fnames=sys.argv[2:]
else:
    skip=False
    fnames=sys.argv[1:]

DELIM='~~~'

for fname in fnames:
    fd=open(fname)
    reader = csv.reader(fd)
    if skip:
        skipped_header = reader.next()
    for row in reader:
        print DELIM.join(row)
