"-----------------------------------------------------------------------
" started from:
" http://www.christopherpoole.net/setting-up-vim-with-youcompleteme.html
"-----------------------------------------------------------------------
set nocompatible
filetype off
syntax on
set clipboard=unnamed
set number
set tabstop=4 shiftwidth=4 expandtab

"-----------------------------------------------------------------------
" Plugins
"-----------------------------------------------------------------------
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'Valloric/YouCompleteMe'
"Plugin 'fatih/vim-go'

"-----------------------------------------------------------------------
" Appearance and Input
"-----------------------------------------------------------------------

filetype plugin indent on
colorscheme mhcolor

" show syntax coloring info under cursor
" leader key is backslash
map <leader>a  :call SyntaxAttr()<CR>

""hmm figure out some good function keys
" F2 - close other windows
" \1 - close other windows
map <F2> :only<CR>
imap <F2> <Esc>:only<CR>a
map <leader>1 :only<CR>
imap <leader>1 <Esc>:only<CR>a

map <F7> :GoRun<CR>

"-----------------------------------------------------------------------
" Unknown stuff follows
"-----------------------------------------------------------------------
"-----------------------------------------------------------------------
"-----------------------------------------------------------------------
"
""-----------------------------------------------------------------------
"" configuring code formatting options
""-----------------------------------------------------------------------
"autocmd FileType *  setlocal formatoptions-=c formatoptions-=r formatoptions-=o
"autocmd FileType go setlocal tabstop=2 
"
""======================================================
"
"call vundle#begin()
"Plugin 'VundleVim/Vundle.vim'
"Plugin 'Valloric/YouCompleteMe'
"call vundle#end()
"
"filetype plugin indent on
