"-----------------------------------------------------------------------
" started from:
" http://www.christopherpoole.net/setting-up-vim-with-youcompleteme.html
"-----------------------------------------------------------------------
set nocompatible
filetype off
syntax on
set clipboard=unnamed
set number
set tabstop=4 shiftwidth=4 expandtab

"-----------------------------------------------------------------------
" Plugins
"-----------------------------------------------------------------------

call plug#begin()
Plug 'fatih/vim-go'
"Plug 'Valloric/YouCompleteMe'
Plug 'Valloric/YouCompleteMe', { 'do': './install.py' }
call plug#end()

"-----------------------------------------------------------------------
" Appearance and Input
"-----------------------------------------------------------------------

filetype plugin indent on
colorscheme mhcolor

" show syntax coloring info under cursor
" leader key is backslash
map <leader>a  :call SyntaxAttr()<CR>

""hmm figure out some good function keys
" F2, \1 - close other windows
map <F2> :only<CR>
imap <F2> <Esc>:only<CR>a
map <leader>1 :only<CR>
imap <leader>1 <Esc>:only<CR>a

map <F7> :GoRun<CR>

"-----------------------------------------------------------------------
" Unknown stuff, is it useful?
"-----------------------------------------------------------------------
"autocmd FileType *  setlocal formatoptions-=c formatoptions-=r formatoptions-=o
"autocmd FileType go setlocal tabstop=2 
"filetype plugin indent on
