#!/bin/sh
rm -f t2.out
(curl -s 'http://localhost:8888/math?op=add&x=4&y=5'
curl -s 'http://localhost:8888/math?op=sub&x=4&y=5'
curl -s 'http://localhost:8888/math?op=mul&x=4&y=5'
curl -s 'http://localhost:8888/math?op=div&x=4&y=5') >t2.out
diff t2.out t2.expected
if test $? -eq 0; then
    rm t2.out
fi
