#!/bin/bash
#
# http://support.fogcreek.com/default.asp?W840
#
#

FBCLI="/opt/fbcli/fbcli --url mysite.fogbugz.com
                        --user myname@example.com
                        --password-file $HOME/.pxdmg"

$FBCLI list
#$FBCLI
#$FBCLI edit 25 'this is a comment' Version=98
